server:
  port: 19093

spring:
  application:
    name: product-service

  #config
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  #mysql 연동
  datasource:
    username: root
    password: password

  # spring data jpa 설정
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  #redis
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

#eureka 연동
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

#zipkin
management:
  endpoints:
    web:
      exposure:
        include: refresh
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0