spring:
  application:
    name: server

server:
  port: 19090

eureka:
  client:
    #유레카 서버에 자기 자신 등록 여부
    register-with-eureka: false
    #유레카 서버로 부터 인스턴스 목록 반환 여부
    fetch-registry: false
    # 유레카 클라이언트가 유레카 서버와 통신하기 위한 http
    serviceUrl:
      defaultZone: http://localhost:19090/eureka/

  instance:
    # 유레카 서버 인스턴스의 호스트 이름 설정
    hostname: localhost