
spring:
  application:
    name: order-service

  #mysql 연동
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/msa_exam
    username: root
    password: password

  # spring data jpa 설정
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  #redis
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

#eureka 연동
server:
  port: 19092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

#zipkin
management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

